update ssh-loadkeys

diff --git a/ssh-loadkeys b/ssh-loadkeys
--- a/ssh-loadkeys
+++ b/ssh-loadkeys
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+SSH_AGENT=`ssh-add -l 2>&1 | grep 'not open'`
+if [[ -n "$SSH_AGENT" ]]; then
+    echo "Error: ssh-agent not started"
+    exit 1
+fi
+
 OS=`uname`
 if [[ "$OS" = "Darwin" ]]; then
     LIBAETPKSS='/usr/local/lib/libaetpkss.dylib'
@@ -9,9 +15,6 @@ fi
 
 AETPKSS=`ssh-add -l | grep $LIBAETPKSS | awk '{print $3}'`
 if [ -z "$AETPKSS" ]; then
-    if [[ "$OS" = "Linux" ]]; then
-        eval `ssh-agent`
-    fi
     ssh-add -s $LIBAETPKSS
 fi
 
